  title: My Docs Page Title
  description: MY description
  url: "https://base/url/site"
  theme: millidocs-dark

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable : true

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  
sass:
  sass_dir: _sass
  style: compressed
